#!/bin/sh

xrdb ~/.Xresources
compton --config ~/.compton.conf
feh --bg-scale ~/essentials/backgrounds/dark-forest.jpg
xmodmap -e 'clear Lock'
xmodmap -e 'keycode 0x42=Escape'
exec ~/essentials/scripts/sysinit/xmonad_start.sh
